services:
  conv:
    build: .
    entrypoint: ["python", "-m", "src.main"]
    volumes:
      - ./data:/data:ro
      - ./output:/app/output
  
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - './output:/app/output'